# Local overrides (gitignored)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zszwwwpzyepuduielccq
spring.datasource.password=Carlomercado@123

# Gmail SMTP (OTP for forgot password)
spring.mail.username=edulibrary67@gmail.com
spring.mail.password=kttaspipdrkzxfby
